Adds split method to port class
leghtas/HFSSdrawpy pull request #31
Opened 2020-05-29 14:04 UTC by MVillius

Pretty self-explanatory

2020-06-15 20:32 UTC, rlescanne requested changes
Qqs petites remarques

2020-06-15 20:32 UTC, rlescanne commented on HFSSdrawpy/core/port.py
> +                     'subnames':self.subnames, 'offsets':self.offsets}
This is not needed here (I think). The save is only required when performing a brief modification of the port (such as when drawing adaptors, the port is temporarily shifted and resized to the other port specs).

2020-06-15 20:32 UTC, rlescanne commented on HFSSdrawpy/core/port.py
> +    def split(self, subnames=[], gap=None):
Je ne sais plus pourquoi mais on n'a pas le droit d'initialiser par défaut à une liste en python. Il vaut mieux mettre un None et propager cette modification dans ton code.

2020-06-15 20:32 UTC, rlescanne commented on HFSSdrawpy/core/port.py
> +            subnames = self.subnames[:-1]
I guess this assumes the last subport defined is the outline/gap. This assumption is not ideal but I guess this is the best solution for now.

2020-06-15 20:32 UTC, rlescanne commented on HFSSdrawpy/core/port.py
> +            layers   = [TRACK, GAP]
To add a little bit of flexibility here, I would replace `TRACK` by the layer of the corresponding subport. I agree that we cannot give this flexibility to `GAP`.

2020-06-26 09:06 UTC, MVillius commented
Done

2020-10-15 09:01 UTC, MVillius commented
I added the possibility to split a multiport (non-CPW) into several multiports, and since the previous Pull Request had not been closed it has been included in the existing one. What do you think Raph?

2021-03-10 15:11 UTC, pierreguilmin commented on HFSSdrawpy/core/port.py
> +            offset2 = -other.offsets[ii]
@MVillius do you think I can merge this modification into master or is it just a specific fix for your work?

2021-03-11 11:11 UTC, MVillius commented on HFSSdrawpy/interfaces/gds_modeler.py
> +TOLERANCE = 1e-9 # for arcs
This is the new standard for everybody in the lab, we should keep 1e-9

2021-03-11 11:23 UTC, MVillius commented on HFSSdrawpy/core/port.py
> +            offset2 = -other.offsets[ii]
This modification makes your life easier when you want to draw adaptors with off-centered multiports. I think I am the only one to do this so you should be able to merge this modification into master seamlessly

2021-03-11 13:07 UTC, merged